=== zapping-vbi/vbi-archive/web/htdocs/zvbi-0.3/networks.dtd
<!--

  Libzvbi Networks Table DTD 1.0

  Copyright (C) 2004 Michael H. Schimek

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 2 as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

  $Id: networks.dtd,v 1.1 2004-07-03 01:38:08 mschimek Exp $

-->
<!ELEMENT networks (country+)>
<!ENTITY % CNI "cni-8301 | cni-8302 | cni-pdc-a | cni-pdc-b | cni-vps">
<!ELEMENT country (name?, country-code, (%CNI;)*, network+)
  -- CNI elements contain only the country code, other bits are zero. -->
<!ELEMENT name (#PCDATA)
  -- Country or network name: UTF-8 encoding. -->
<!ELEMENT country-code (#PCDATA)
  -- RFC 1766 / ISO 3166-1 alpha-2, e.g. US, GB, FR, DE. -->
<!ELEMENT network (name, (%CNI; | ttx-header)+)>
<!ATTLIST network id ID #REQUIRED>
<!ELEMENT cni-8301 (#PCDATA)
  -- 4 digit Teletext packet 8/30 format 1 CNI: 0x([0-9]|[a-f]|[A-F])+,
     cccc cccc nnnn nnnn in binary. -->
<!ELEMENT cni-8302 (#PCDATA)
  -- 4 digit Teletext packet 8/30 format 2 CNI: 0x([0-9]|[a-f]|[A-F])+,
     cccc cccc nnnn nnnn. -->
<!ELEMENT cni-pdc-a (#PCDATA)
  -- 5 digit PDC Method A CNI:
     0x([0-9]|[a-f]|[A-F])([0-9]|[a-f]|[A-F])[0-9][0-9][0-9],
     cccc cccc nnnn nnnn nnnn. (This is a hex/bcd number.) -->
<!ELEMENT cni-pdc-b (#PCDATA)
  -- 4 digit PDC Method B CNI: 0x3([0-9]|[a-f]|[A-F])+,
     0011 cccc nnnn nnnn. -->
<!ELEMENT cni-vps (#PCDATA)
  -- 3 digit VPS CNI: 0x([0-9]|[a-f]|[A-F])+, cccc nnnn nnnn. -->
<!ELEMENT ttx-header (#PCDATA)
  -- Teletext header for identification of networks which transmit
     Teletext but no CNI: up to 32 characters starting at column 8,
     in raw Teletext encoding, code range 0x20 to 0x7E. 0x23 (number
     sign) stands for digit [0-9], 0x3F (question mark) for
     any character. -->
<!--
Local Variables:
mode: sgml
indent-tabs-mode: nil
coding: utf-8
End:
-->

=== zapping-vbi/vbi-archive/web/htdocs/zvbi-0.3/networks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE networks SYSTEM "http://zapping.sourceforge.net/zvbi-0.3/networks.dtd">
<!--

  Libzvbi Networks Table

  Copyright (C) 2000-2006 Michael H. Schimek

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License version 2 as
  published by the Free Software Foundation.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

  ============================================================================

  This information comes from TR 101 231 EBU rev. 2006-04b, www.ebu.ch,

  Table A.1: Register of Country and Network Identification
             (CNI) codes for Teletext based systems

  Table B.1: VPS CNI Codes used in Germany, Switzerland and Austria

  and from ETS 300 231 "Specification of the domestic video Programme
    Delivery Control system (PDC)"

  Please send corrections and additions to mschimek@users.sourceforge.net.

  ============================================================================

  Highest network id is n685 (arbitrary number used to distinguish
    networks in libzvbi-0.2).

  $Id: networks.xml,v 1.4 2006-05-03 03:28:13 mschimek Exp $

-->
<networks>
  <country>
    <name>Albania</name>
    <country-code>AL</country-code>
    <cni-8302>0x1900</cni-8302>
  </country>

  <country>
    <name>Algeria</name>
    <country-code>DZ</country-code>
    <cni-8302>0x1200</cni-8302>
  </country>

  <country>
    <name>Andorra</name>
    <country-code>AD</country-code>
    <cni-8302>0x1300</cni-8302>
  </country>

  <country>
    <name>Austria</name>
    <country-code>AT</country-code>
    <cni-8301>0x4300</cni-8301>
    <cni-8302>0x1A00</cni-8302>
    <network id="n193">
      <name>ORF 1</name>
      <cni-8301>0x4301</cni-8301>
      <cni-vps>0x0AC1</cni-vps>
      <pdc>
        <near>311-315</near>
        <near>321-325</near>
	<far depth="8">346-353</far>
	<symbol code="bilingual" color="red">°*</symbol>
	<symbol code="bw" color="red">s/w</symbol>
	<symbol code="dd51" color="red">DD</symbol>
	<symbol code="description" color="red">HF</symbol>
	<symbol code="ds" color="red">DS</symbol>
	<symbol code="stereo" color="red">°°</symbol>
	<symbol code="subtitles" color="red">UT</symbol>
	<symbol code="surround" color="red">SS</symbol>
	<symbol code="ws169" color="red">16:9</symbol>
	<symbol code="children" color="red">K+</symbol>
	<symbol code="mature" color="red">X</symbol>
	<symbol code="adult" color="red">O</symbol>
      </pdc>
    </network>
    <network id="n194">
      <name>ORF 2</name>
      <cni-8301>0x4302</cni-8301>
      <cni-vps>0x0AC2</cni-vps>
    </network>
    <network id="n195">
      <name>ORF 3</name>
      <cni-vps>0x0AC3</cni-vps>
    </network>
    <network id="n680">
      <name>ORF Sport+</name>
      <cni-vps>0x0AC4</cni-vps>
    </network>
    <network id="n524">
      <name>TW1</name>
      <cni-vps>0x0AC7</cni-vps>
      <!-- Transmits cni-vps 0xAC1 (ORF 1)? -->
      <ttx-header>###?TW1  </ttx-header>
    </network>
    <network id="n681">
      <name>Nick - Viva</name>
      <cni-vps>0x0AC8</cni-vps>
    </network>
    <network id="n682">
      <name>MTV Austria</name>
      <cni-vps>0x0AC9</cni-vps>
    </network>
    <network id="n205">
      <name>ATV+</name>
      <cni-8301>0x430C</cni-8301>
      <cni-vps>0x0ACA</cni-vps>
      <pdc>
        <near date-row="0" date-format=" %d.%m. " time-format="%H.%M">301-304</near>
        <near date-row="0" date-format=" %d.%m. " time-format="%H.%M" time-offset="1440">305-308</near>
        <near date-row="0" date-format=" %d.%m. " time-format="%H.%M" time-offset="2880" depth="4">309</near>
      </pdc>
    </network>
    <network id="n196">
      <name>ORF Burgenland</name>
      <cni-vps>0x0ACB</cni-vps>
    </network>
    <network id="n197">
      <name>ORF Kärnten</name>
      <cni-vps>0x0ACC</cni-vps>
    </network>
    <network id="n198">
      <name>ORF Niederösterreich</name>
      <cni-vps>0x0ACD</cni-vps>
    </network>
    <network id="n199">
      <name>ORF Oberösterreich</name>
      <cni-vps>0x0ACE</cni-vps>
    </network>
    <network id="n200">
      <name>ORF Salzburg</name>
      <cni-vps>0x0ACF</cni-vps>
    </network>
    <network id="n201">
      <name>ORF Steiermark</name>
      <cni-vps>0x0AD0</cni-vps>
    </network>
    <network id="n202">
      <name>ORF Tirol</name>
      <cni-vps>0x0AD1</cni-vps>
    </network>
    <network id="n203">
      <name>ORF Vorarlberg</name>
      <cni-vps>0x0AD2</cni-vps>
    </network>
    <network id="n204">
      <name>ORF Wien</name>
      <cni-vps>0x0AD3</cni-vps>
    </network>
    <network id="n525">
      <name>UPC Telekabel</name>
      <ttx-header>###?Wiener?Kabel?Text  </ttx-header>
    </network>
  </country>

  <country>
    <name>Belarus</name>
    <country-code>BY</country-code>
    <cni-8302>0x1700</cni-8302>
  </country>

  <country>
    <name>Belgium</name>
    <country-code>BE</country-code>
    <cni-8301>0x3200</cni-8301>
    <cni-8302>0x1600</cni-8302>
    <network id="n379">
      <name>AB3</name>
      <cni-8301>0x320C</cni-8301>
    </network>
    <network id="n380">
      <name>AB4e</name>
      <cni-8301>0x320D</cni-8301>
    </network>
    <network id="n1">
      <name>VRT TV1</name>
      <cni-8301>0x3201</cni-8301>
      <cni-8302>0x1601</cni-8302>
      <cni-pdc-b>0x3603</cni-pdc-b>
    </network>
    <network id="n5">
      <name>CANVAS</name>
      <cni-8301>0x3202</cni-8301>
      <cni-8302>0x1602</cni-8302>
      <cni-pdc-b>0x3602</cni-pdc-b>
    </network>
    <network id="n3">
      <name>RTBF 1</name>
      <cni-8301>0x3203</cni-8301>
    </network>
    <network id="n4">
      <name>RTBF 2</name>
      <cni-8301>0x3204</cni-8301>
    </network>
    <network id="n7">
      <name>VTM</name>
      <cni-8301>0x3205</cni-8301>
      <cni-8302>0x1605</cni-8302>
      <cni-pdc-b>0x3605</cni-pdc-b>
    </network>
    <network id="n2">
      <name>Kanaal2</name>
      <cni-8301>0x3206</cni-8301>
      <cni-8302>0x1606</cni-8302>
      <cni-pdc-b>0x3606</cni-pdc-b>
    </network>
    <network id="n381">
      <name>RTBF Sat</name>
      <cni-8301>0x3207</cni-8301>
    </network>
    <network id="n382">
      <name>RTL-TV1</name>
      <cni-8301>0x3209</cni-8301>
    </network>
    <network id="n383">
      <name>CLUB-RTL</name>
      <cni-8301>0x320A</cni-8301>
    </network>
    <network id="n6">
      <name>VT4</name>
      <cni-8301>0x0404</cni-8301>
      <cni-8302>0x1604</cni-8302>
      <cni-pdc-b>0x3604</cni-pdc-b>
    </network>
    <network id="n384">
      <name>JIM.tv</name>
      <cni-8301>0x320F</cni-8301>
    </network>
    <network id="n385">
      <name>PLUG TV</name>
      <cni-8301>0x3225</cni-8301>
    </network>
    <network id="n386">
      <name>RTV-Kempen</name>
      <cni-8301>0x3210</cni-8301>
    </network>
    <network id="n387">
      <name>RTV-Mechelen</name>
      <cni-8301>0x3211</cni-8301>
    </network>
    <network id="n388">
      <name>MCM Belgium</name>
      <cni-8301>0x3212</cni-8301>
    </network>
    <network id="n389">
      <name>Vitaya</name>
      <cni-8301>0x3213</cni-8301>
    </network>
    <network id="n390">
      <name>WTV</name>
      <cni-8301>0x3214</cni-8301>
    </network>
    <network id="n391">
      <name>FocusTV</name>
      <cni-8301>0x3215</cni-8301>
    </network>
    <network id="n392">
      <name>Be 1 ana</name>
      <cni-8301>0x3216</cni-8301>
    </network>
    <network id="n393">
      <name>Be 1 num</name>
      <cni-8301>0x3217</cni-8301>
    </network>
    <network id="n394">
      <name>Be Ciné 1</name>
      <cni-8301>0x3218</cni-8301>
    </network>
    <network id="n395">
      <name>Be Sport 1</name>
      <cni-8301>0x3219</cni-8301>
    </network>
    <network id="n530">
      <name>Be 1 + 1h</name>
      <cni-8301>0x32A7</cni-8301>
    </network>
    <network id="n531">
      <name>Be Ciné 2</name>
      <cni-8301>0x32A8</cni-8301>
    </network>
    <network id="n532">
      <name>Be Sport 2</name>
      <cni-8301>0x32A9</cni-8301>
    </network>
    <network id="n396">
      <name>PRIME Sport 1</name>
      <cni-8301>0x321A</cni-8301>
    </network>
    <network id="n397">
      <name>PRIME Sport 2</name>
      <cni-8301>0x321B</cni-8301>
    </network>
    <network id="n398">
      <name>PRIME Action</name>
      <cni-8301>0x321C</cni-8301>
    </network>
    <network id="n399">
      <name>PRIME One</name>
      <cni-8301>0x321D</cni-8301>
    </network>
    <network id="n400">
      <name>TV Limburg</name>
      <cni-8301>0x3221</cni-8301>
    </network>
    <network id="n401">
      <name>Kanaal 3</name>
      <cni-8301>0x3222</cni-8301>
    </network>
    <network id="n402">
      <name>Ring TV</name>
      <cni-8301>0x320E</cni-8301>
    </network>
    <network id="n403">
      <name>TV Brussel</name>
      <cni-8301>0x321E</cni-8301>
    </network>
    <network id="n404">
      <name>AVSe</name>
      <cni-8301>0x321F</cni-8301>
    </network>
    <network id="n405">
      <name>ATV</name>
      <cni-8301>0x3223</cni-8301>
    </network>
    <network id="n406">
      <name>ROB TV</name>
      <cni-8301>0x3224</cni-8301>
    </network>
    <network id="n407">
      <name>Télé Bruxelles</name>
      <cni-8301>0x3230</cni-8301>
    </network>
    <network id="n408">
      <name>Télésambre</name>
      <cni-8301>0x3231</cni-8301>
    </network>
    <network id="n409">
      <name>TV Com</name>
      <cni-8301>0x3232</cni-8301>
    </network>
    <network id="n410">
      <name>Canal Zoom</name>
      <cni-8301>0x3233</cni-8301>
    </network>
    <network id="n411">
